version: '3.8'

# This should be added in .gitignore

services:
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - localDbEnv:/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: table
    restart: unless-stopped

volumes:
  localDbEnv:
    external: false
