version: '3.8'

# This should be added in .gitignore

services:
  postgres:
    ports:
      - "5432:5432"
    volumes:
      - localDbEnv:/postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    restart: unless-stopped
    networks:
      - localDbNetwork

  pgadmin:
    container_name: pgadmin
    image: dpage/pgadmin4
    restart: unless-stopped
    ports:
      - "5002:5002"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.admin
      PGADMIN_DEFAULT_PASSWORD: admin
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - localDbEnv:/pgadmin
    networks:
      - localDbNetwork
    depends_on:
      - postgres

networks:
  localDbNetwork:
    driver: bridge

volumes:
  localDbEnv:
    external: false
